### ISSUE TITLE
Dedicated server spammed since last update

### ISSUE THREAD

**Issue by Grumpy35** [Konijima/PlayerConnectionMessage#1]
Hello! Since your most recent update my dedicated server has been continuously spammed by the same error message. 
Here it is:

Callframe at: get
function: OnTick -- file: MainServer.lua line # 50 | MOD: Player Connection Message

ERROR: General     , 1687127029372> 510,916,398> ExceptionLogger.logException> Exception thrown java.lang.reflect.InvocationTargetException at GeneratedMethodAccessor33.invoke.
ERROR: General     , 1687127029372> 510,916,398> DebugLogStream.printException> Stack trace:
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
        at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
        at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:188)
        at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
        at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
        at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
        at zombie.Lua.Event.trigger(Event.java:64)
        at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
        at zombie.gameStates.IngameState.updateInternal(IngameState.java:1624)
        at zombie.gameStates.IngameState.update(IngameState.java:1333)
        at zombie.network.GameServer.main(GameServer.java:903)
Caused by: java.lang.IndexOutOfBoundsException: Index 27 out of bounds for length 6
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.get(Unknown Source)
        ... 18 more

**Comment by Grumpy35** [comment]
Also, I noticed that it announces when staff logs on even though I have hide Admin and hide staff checked. Just thought I'd include that in with the information.

**Comment by Konijima** [comment]
> Also, I noticed that it announces when staff logs on even though I have hide Admin and hide staff checked. Just thought I'd include that in with the information.

If you are admin it will show even if hidden.

**Comment by Grumpy35** [comment]
> > Also, I noticed that it announces when staff logs on even though I have hide Admin and hide staff checked. Just thought I'd include that in with the information.
> 
> If you are admin it will show even if hidden.

Ah I see. Thank you very much. I like being hidden from the players when I log on. lol

**Comment by Konijima** [comment]
> > > Also, I noticed that it announces when staff logs on even though I have hide Admin and hide staff checked. Just thought I'd include that in with the information.
> > 
> > 
> > If you are admin it will show even if hidden.
> 
> Ah I see. Thank you very much. I like being hidden from the players when I log on. lol

Oh yeah, well I mean, admin will see the messages no matter what the settings are.
Players on the other hand will not see the messages if `hideAdmin` is true.

**Comment by Konijima** [comment]
Please let me know if this is fixed on your side.
@Grumpy35
